name: issue trigger workflow
on:
  issues:
    types: [opened, edited, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

jobs:
  issue-job:
    runs-on: ubuntu-latest
    steps:
      - name: Informações da issue
        run: |
          echo "Ação disparada por issue"
          echo "Número da Issue: ${{ github.event.issue.number }}"
          echo "Título da Issue: ${{ github.event.issue.title }}"
          echo "Estado da Issue: ${{ github.event.issue.state }}"
          echo "Autor da Issue: ${{ github.event.issue.user.login }}"
          echo "labels: ${{join(github.event.issue.labels.*.name, ', ')}}"
          echo "Ação realizada: ${{ github.event.action }}"

      - name: Resposta automatica (nova issue)
        if: github.event.action == 'opened'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Obrigado por abrir a issue! Nossa equipe irá analisar em breve."
            })