name: "Estrutura de diretorios e arquivos"

on:
    push:
        branches: [ main ]
    workflow_dispatch:

env:
    NODE_VERSION: '18'

jobs:
    demonstrar_estrutura:
        name: "demonstrar estrutura basica"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codigo
              uses: actions/checkout@v4

            - name: Mostrar estrutura .github/workflows
              run: |
                echo " == ESTRUTURA DE DIRETÓRIOS E ARQUIVOS .github/workflows == "
                ls -la .github/workflows
                echo ""
                echo " Total de workflows: $(ls -1 .github/workflows | wc -l)"

            - name: Elementos obrigatórios do workflow
              run: |
                echo " == ELEMENTOS OBRIGATÓRIOS DO WORKFLOW == "
                echo " 1. name: Nome do workflow"
                echo " 2. on: Evento(s) que disparam o workflow"
                echo " 3. jobs: Definição dos trabalhos a serem executados"
                echo " 4. runs-on: Ambiente onde o trabalho será executado"
                echo " 5. steps: Definição dos passos a serem executados"
                echo ""
                echo " Total de elementos obrigatórios: 5:"

            - name: Variáveis e contextos do workflow
              run: |
                echo " == VARIÁVEIS E CONTEXTOS DO WORKFLOW == "
                echo " Variáveis env: {env.NODE_vERSION} "
                echo " 1. env: Definição de variáveis de ambiente"
                echo " 2. contextos: Acesso a informações do workflow, job, runner e etc. "
                echo ""
                echo " Total de variáveis e contextos: 2"